routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'Auth\LoginController@showLoginForm');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::middleware('auth')->prefix('admin')->namespace('Admin')->group(function () {
    Route::get('/dashboard/{id?}', 'DashboardController@index')->name('dashboard.index');
    Route::get('/report', 'ReportController@index')->name('report.index');
    Route::post('/report', 'ReportController@report')->name('report.report');
    Route::resources([
        'office' => 'OfficeController',
        'employee' => 'EmployeeController',
        'unit' => 'UnitController',
        'indicator' => 'IndicatorController',
        // 'performance-indicator' => 'PerformanceIndicatorController'
    ]);

    Route::resource('performance-indicator', 'PerformanceIndicatorController')->except([
        'edit'
    ]);
    Route::get('/performance-indicator/{office_id}/{year}/edit', 'PerformanceIndicatorController@edit')->name('performance-indicator.edit');
});


Route::prefix('api')->namespace('Api')->group(function () {
    Route::get('/office', 'PerformanceIndicatorController@offices');
    Route::get('/indicator/{id}', 'PerformanceIndicatorController@indicators');
    Route::get('/years/{id}', 'PerformanceIndicatorController@years');
});

app/Models/PerformanceIndicator.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PerformanceIndicator extends Model
{
    public function indicator()
    {
        return $this->belongsTo('App\Models\Indicator', 'indicator_id');
    }

    public function office()
    {
        return $this->belongsTo('App\Models\Office', 'office_id');
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'created_by');
    }
}

app/Http/Controllers/Admin/PerformanceIndicatorController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\Controller;
use App\Models\PerformanceIndicator;
use App\Models\Indicator;
use App\Models\Office;

class PerformanceIndicatorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $performance_indicators = PerformanceIndicator::whereHas('user.offices', function ($q) {
            if (Auth::user()->hasRole('employee')) {
                $q->where('id', session('office_id'));
            }
        })
        ->orderBy('id', 'desc')->groupBy('year')->paginate(10);
        return view('admin.performance_indicator.index', compact('performance_indicators'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->hasRole('employee')) {
            $office = Auth::user()->offices->first();
            $years = $this->years(session('office_id'));
            $indicators = Indicator::where('office_id', Auth::user()->offices->first()->id)->with('unit')->get();
            return view('admin.performance_indicator.create', compact('office','years','indicators'));
        }
        else {
            return view('admin.performance_indicator.create');
        }
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'year' => 'required',
        ]);

        DB::transaction(function () use ($request) {
            
            for ($i = 0; $i < count($request->id_indicators); $i++) 
            {
                if ($request->amount_target[$i] !== null) {
                    $performance_indicator = new PerformanceIndicator;
                    $performance_indicator->office_id = session('office_id');
                    $performance_indicator->indicator_id = $request->id_indicators[$i];
                    $performance_indicator->year = $request->year;
                    $performance_indicator->amount_target = $request->amount_target[$i];

                    if ($request->amount_realization[$i] !== null) {                        
                        $performance_indicator->amount_realization = $request->amount_realization[$i];
                        $performance_indicator->percentage_realization = ($request->amount_realization[$i] / $request->amount_target[$i]) * 100;
                    }

                    $performance_indicator->created_by = Auth::id();
                    $performance_indicator->save();
                }
            }

        });

        return redirect()->route('performance-indicator.index')->with('success', 'store');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($office_id, $year)
    {
        $indicators = Indicator::where('office_id', $office_id)->get();
        $office = Office::find($office_id);
        $performance_indicators = PerformanceIndicator::where([
            ['office_id', '=', $office_id],
            ['year', '=', $year]
        ])->get();

        foreach($indicators as $key => $indicator) {
            $found = false;
            foreach($performance_indicators as $performance_indicator) {
                if ($indicator->id === $performance_indicator->indicator_id) {
                    $found = true;
                    $filled_performance_indicators[$key]['id'] = $performance_indicator->id;
                    $filled_performance_indicators[$key]['indicator_id'] = $indicator->id;
                    $filled_performance_indicators[$key]['indicator_name'] = $indicator->name;
                    $filled_performance_indicators[$key]['amount_target'] = $performance_indicator->amount_target;
                    $filled_performance_indicators[$key]['amount_realization'] = $performance_indicator->amount_realization;
                    $filled_performance_indicators[$key]['percentage_realization'] = $performance_indicator->percentage_realization;
                    $filled_performance_indicators[$key]['unit_name'] = $indicator->unit->name;
                }
            }

            if (!$found) {
                $filled_performance_indicators[$key]['id'] = null;
                $filled_performance_indicators[$key]['indicator_id'] = $indicator->id;
                $filled_performance_indicators[$key]['indicator_name'] = $indicator->name;
                $filled_performance_indicators[$key]['amount_target'] = null;
                $filled_performance_indicators[$key]['amount_realization'] = null;
                $filled_performance_indicators[$key]['percentage_realization'] = null;
                $filled_performance_indicators[$key]['unit_name'] = $indicator->unit->name;
            }
        }
        // dd($filled_performance_indicators);
        return view('admin.performance_indicator.edit', compact('office','year','performance_indicators','indicators','filled_performance_indicators'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::transaction(function () use ($request) 
        {
            for ($i = 0; $i < count($request->id_performance_indicators); $i++) 
            {
                if ($request->id_performance_indicators[$i] !== null) {
                    $performance_indicator = PerformanceIndicator::find($request->id_performance_indicators[$i]);
                    $performance_indicator->delete();
                }
            }

            for ($i = 0; $i < count($request->id_indicators); $i++) 
            {
                if ($request->amount_target[$i] !== null) {
                    $performance_indicator = new PerformanceIndicator;
                    $performance_indicator->office_id = $request->office_id;
                    $performance_indicator->indicator_id = $request->id_indicators[$i];
                    $performance_indicator->year = $request->year;
                    $performance_indicator->amount_target = $request->amount_target[$i];

                    if ($request->amount_realization[$i] !== null) {                        
                        $performance_indicator->amount_realization = $request->amount_realization[$i];
                        $performance_indicator->percentage_realization = ($request->amount_realization[$i] / $request->amount_target[$i]) * 100;
                    }

                    $performance_indicator->created_by = Auth::id();
                    $performance_indicator->save();
                }
            }
        });

        return redirect()->route('performance-indicator.index')->with('success', 'update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $performance_indicator = PerformanceIndicator::find($id);
        $performance_indicator->delete();
        
        return back()->with('success', 'destroy');
    }

    private function years($id)
    {
        $performance_indicators = PerformanceIndicator::where('office_id', $id)->groupBy('year')->get();
        foreach (range(2019, 2000) as $key => $year) {
            $years[$key]['name'] = $year;
            
            if ($performance_indicators->count() > 0) {
                $found = false;
                foreach ($performance_indicators as $performance_indicator) {
                    if ($performance_indicator->year === $year) {
                        $found = true;
                        $years[$key]['available'] = false;
                    } 
                }

                if (!$found) {
                    $years[$key]['available'] = true;
                }
            }
            else {
                $years[$key]['available'] = true;
            }
        } 
        return $years;
    }
}

app/Http/Controllers/Api/PerformanceIndicatorController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Office;
use App\Models\Indicator;
use App\Models\PerformanceIndicator;

class PerformanceIndicatorController extends Controller
{
    public function offices()
    {
        return Office::all();
    }

    public function indicators($id)
    {
        return Indicator::where('office_id', $id)->with('unit')->get();
    }

    public function years($id)
    {
        $performance_indicators = PerformanceIndicator::where('office_id', $id)->groupBy('year')->get();
        foreach (range(2019, 2000) as $key => $year) {
            $years[$key]['name'] = $year;
            
            if ($performance_indicators->count() > 0) {
                $found = false;
                foreach ($performance_indicators as $performance_indicator) {
                    if ($performance_indicator->year === $year) {
                        $found = true;
                        $years[$key]['available'] = false;
                    } 
                }

                if (!$found) {
                    $years[$key]['available'] = true;
                }
            }
            else {
                $years[$key]['available'] = true;
            }
        } 
        return $years;
    }
    
}

resources/views/admin/performance_indicator/create.blade.php
@extends('admin.templates.default')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Tambah Data Indikator Kinerja</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12">
                <div class="card">
                    <form action="{{ route('performance-indicator.store') }}" method="post">
                        @csrf
                        <div class="card-header">
                            <h4>Form</h4>
                        </div>
                        <div class="card-body">

                            @role('admin')
                                <div id="app">
                                    <performance-indicator-create></performance-indicator-create>
                                </div>      
                            @endrole      
                            
                            @role('employee')
                                @include('admin.performance_indicator.partials._indicator_table')
                            @endrole
                        </div>
                        <div class="card-footer text-right">
                            <button class="btn btn-primary mr-1" type="submit">Simpan</button>
                            <a href="{{ route('performance-indicator.index') }}" class="btn btn-secondary">Batal</a>
                        </div>
                    </form>    
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@push('scripts')
<script src="{{ asset('js/app.js') }}"></script>
@endpush

resources/views/admin/performance_indicator/edit.blade.php
@extends('admin.templates.default')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Perbarui Data Indikator Kinerja</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12">
                <div class="card">
                    <form action="{{ route('performance-indicator.update', $office->id) }}" method="post">
                        @csrf
                        @method('PUT')

                        <div class="card-header">
                            <h4>Form</h4>
                        </div>
                        <div class="card-body">
                            <div class="form-group row">
                                <label for="office_id" class="col-sm-2 col-form-label">Dinas / OPD</label>
                                <div class="col-sm-10">
                                    {{ $office->name }}
                                    <input type="hidden" name="office_id" value="{{ $office->id }}">
                                </div>
                            </div>
                    
                            <div class="form-group row">
                                <label for="year" class="col-sm-2 col-form-label">Tahun</label>
                                <div class="col-sm-2">
                                    {{ $year }}    
                                    <input type="hidden" name="year" value="{{ $year }}">    
                                </div>
                            </div>
                            
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Indikator Kinerja Utama</label>
                                <div class="col-sm-10">
                                    <table class="table table-bordered">
                                        <tr>
                                            <th>Indikator</th>
                                            <th>Target</th>
                                            <th>Ralisasi</th>
                                            <th>Satuan</th>
                                            <th>%</th>
                                        </tr>
                    
                                        @foreach($filled_performance_indicators as $key => $filled_performance_indicator)
                                        
                                        <input type="hidden" name="id_indicators[]" value="{{ $filled_performance_indicator['indicator_id'] }}">
                                        <input type="hidden" name="id_performance_indicators[]" value="{{ $filled_performance_indicator['id'] }}">

                                        <tr>
                                            <td>{{ $filled_performance_indicator['indicator_name'] }}</td>
                                            <td><input type="text" class="form-control" name="amount_target[]" value="{{ $filled_performance_indicator['amount_target'] }}"></td>
                                            <td><input type="text" class="form-control" name="amount_realization[]" value="{{ $filled_performance_indicator['amount_realization'] }}"></td>
                                            <td>{{ $filled_performance_indicator['unit_name'] }}</td>
                                            <td>{{ number_format($filled_performance_indicator['percentage_realization'], 2) }}</td>
                                            
                                        </tr>
                                        @endforeach
                                    </table>
                                </div>
                            </div>                   
                        </div>
                        <div class="card-footer text-right">
                            <button class="btn btn-primary mr-1" type="submit">Simpan</button>
                            <a href="{{ route('performance-indicator.index') }}" class="btn btn-secondary">Batal</a>
                        </div>
                    </form>    
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/admin/performance_indicator/index.blade.php
@extends('admin.templates.default')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Indikator Kinerja</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Daftar Tabel</h4>
                    </div>
                    <div class="card-body p-3">
                        <div class="row">
                            <div class="col-sm-9">
                                <a id="add" href="{{ route('performance-indicator.create') }}" class="btn btn-primary btn-icon icon-left"><i class="fas fa-plus"></i> Tambah</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body p-1">
                        <div class="table-responsive">
                            <table class="table table-striped table-md">
                                <tr>
                                    <th>Kantor</th>
                                    <th>Tahun</th>
                                    <th>Action</th>
                                </tr>

                                @foreach($performance_indicators as $performance_indicator)
                                <tr>
                                    <td>{{ $performance_indicator->office->name }}</td>
                                    <td>{{ $performance_indicator->year }}</td>
                                    <td>
                                        <form action="{{ route('performance-indicator.destroy', $performance_indicator) }}" method="post">
                                            @csrf
                                            @method("DELETE")
                                            
                                            <a href="{{ route('performance-indicator.edit', [$performance_indicator->office_id, $performance_indicator->year]) }}" class="btn btn-info btn-icon icon-left"><i class="fas fa-edit"></i> Perbarui</a>
                                            <button onclick="return confirm('Yakin ingin menghapus?')" type="submit" class="btn btn-danger btn-icon icon-left"><i class="fas fa-trash"></i> Hapus</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <nav class="d-inline-block">
                            {{ $performance_indicators->links() }}
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@include('admin.templates.partials._notifications')