routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'Auth\LoginController@showLoginForm');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::middleware('auth')->prefix('admin')->namespace('Admin')->group(function () {
    Route::get('/dashboard/{id?}', 'DashboardController@index')->name('dashboard.index');
    Route::get('/report', 'ReportController@index')->name('report.index');
    Route::post('/report', 'ReportController@report')->name('report.report');
    Route::resources([
        'office' => 'OfficeController',
        'employee' => 'EmployeeController',
        'unit' => 'UnitController',
        'indicator' => 'IndicatorController',
        // 'performance-indicator' => 'PerformanceIndicatorController'
    ]);

    Route::resource('performance-indicator', 'PerformanceIndicatorController')->except([
        'edit'
    ]);
    Route::get('/performance-indicator/{office_id}/{year}/edit', 'PerformanceIndicatorController@edit')->name('performance-indicator.edit');
});


Route::prefix('api')->namespace('Api')->group(function () {
    Route::get('/office', 'PerformanceIndicatorController@offices');
    Route::get('/indicator/{id}', 'PerformanceIndicatorController@indicators');
    Route::get('/years/{id}', 'PerformanceIndicatorController@years');
});

app/Models/Indicator.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Indicator extends Model
{
    public function children()
    {
        return $this->hasMany('App\Models\Indicator', 'indicator_id');
    }

    public function unit()
    {
        return $this->belongsTo('App\Models\Unit', 'unit_id');
    }

    public function office()
    {
        return $this->belongsTo('App\Models\Office', 'office_id');
    }

    public function performance_indicator()
    {
        return $this->hasOne('App\Models\PerformanceIndicator', 'indicator_id');
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'created_by');
    }
}

app/Http/Controllers/Admin/IndicatorController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use App\Models\Indicator;
use App\Models\Unit;
use App\Models\Office;
use App\Models\User;

class IndicatorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $indicators = Indicator::whereHas('user.offices', function ($q) {
            if (Auth::user()->hasRole('employee')) {
                $q->where('id', session('office_id'));
            }
        })
        ->orderBy('id', 'desc')->paginate(10);
        return view('admin.indicator.index', compact('indicators', $indicators));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $offices = Office::all();
        $units = Unit::orderBy('name', 'asc')->get();
        return view('admin.indicator.create', compact('offices','units'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            // 'office_id' => 'required',
            'name' => 'required',
            'unit_id' => 'required'
        ]);

        $indicator = new Indicator;
        $indicator->name = $request->name;
        $indicator->unit_id = $request->unit_id;
        $indicator->created_by = Auth::id();

        if (Auth::user()->hasRole('admin')) {
            $indicator->office_id = $request->office_id;
        }else {
            $indicator->office_id = session('office_id');
        }

        // if ($request->filled('indicator_id'))
        //     $indicator->indicator_id = $request->indicator_id;

        $indicator->save();
        
        return redirect()->route('indicator.index')->with('success', 'store');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $offices = Office::all();
        $indicator = Indicator::find($id);
        $units = Unit::orderBy('name', 'asc')->get();
        return view('admin.indicator.edit', compact('indicator','units','offices'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required',
            'unit_id' => 'required'
        ]);

        $indicator = Indicator::find($id);
        $indicator->name = $request->name;
        $indicator->unit_id = $request->unit_id;
        $indicator->updated_by = Auth::id();

        if (Auth::user()->hasRole('admin')) {
            $indicator->office_id = $request->office_id;
        }else {
            $indicator->office_id = session('office_id');
        }
        
        $indicator->update();
        
        return redirect()->route('indicator.index')->with('success', 'update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $indicator = Indicator::find($id);
        $indicator->delete();
        
        return back()->with('success', 'destroy');
    }
}

resources/views/admin/indicator/create.blade.php
@extends('admin.templates.default')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Tambah Data Indikator</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12">
                <div class="card">
                    <form action="{{ route('indicator.store') }}" method="post">
                        @csrf
                        <div class="card-header">
                            <h4>Form</h4>
                        </div>
                        <div class="card-body">

                            @role('admin')
                            <div class="form-group row">
                                <label for="office_id" class="col-sm-2 col-form-label">Dinas / SKPD</label>
                                <div class="col-sm-10">
                                    <select class="form-control"name="office_id" required="true">
                                        <option value=""> - </option>
                                        @foreach ($offices as $office)
                                            <option value="{{ $office->id }}" {{ $office->id === old('office_id') ? 'selected' : '' }}>{{ $office->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('office_id')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>
                            @endrole
                    
                            <div class="form-group row">
                                <label for="name" class="col-sm-2 col-form-label">Nama</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name') }}" required="true">
                                    @error('name')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="unit_id" class="col-sm-2 col-form-label">Satuan</label>
                                <div class="col-sm-10">
                                    <select class="form-control"name="unit_id" required="true">
                                        <option value=""> - </option>
                                        @foreach ($units as $unit)
                                            <option value="{{ $unit->id }}">{{ $unit->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('unit_id')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>
                    
                        </div>
                        <div class="card-footer text-right">
                            <button class="btn btn-primary mr-1" type="submit">Simpan</button>
                            <a href="{{ route('indicator.index') }}" class="btn btn-secondary">Batal</a>
                        </div>
                    </form>    
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/admin/indicator/edit.blade.php
@extends('admin.templates.default')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Perbarui Data Indikator</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12">
                <div class="card">
                    <form action="{{ route('indicator.update', $indicator) }}" method="post">
                        @csrf
                        @method('PUT')

                        <div class="card-header">
                            <h4>Form</h4>
                        </div>
                        <div class="card-body">

                            @role('admin')
                            <div class="form-group row">
                                <label for="office_id" class="col-sm-2 col-form-label">Dinas / SKPD</label>
                                <div class="col-sm-10">
                                    <select class="form-control"name="office_id" required="true">
                                        <option value=""> - </option>
                                        @foreach ($offices as $office)
                                            <option value="{{ $office->id }}" {{ $office->id === old('office_id', $indicator->office_id) ? 'selected' : '' }}>{{ $office->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('office_id')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>
                            @endrole
                    
                            <div class="form-group row">
                                <label for="name" class="col-sm-2 col-form-label">Nama</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $indicator->name) }}">
                                    @error('name')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="unit_id" class="col-sm-2 col-form-label">Satuan</label>
                                <div class="col-sm-10">
                                    <select class="form-control"name="unit_id" required="true">
                                        <option value=""> - </option>
                                        @foreach ($units as $unit)
                                            <option value="{{ $unit->id }}" {{ $unit->id === $indicator->unit_id ? 'selected' : '' }}>{{ $unit->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('unit_id')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>

                        </div>
                        <div class="card-footer text-right">
                            <button class="btn btn-primary mr-1" type="submit">Simpan</button>
                            <a href="{{ route('indicator.index') }}" class="btn btn-secondary">Batal</a>
                        </div>
                    </form>    
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/admin/indicator/index.blade.php
@extends('admin.templates.default')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Indikator</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Daftar Tabel</h4>
                    </div>
                    <div class="card-body p-0">
                        <div class="col-sm-12">
                            <a href="{{ route('indicator.create') }}" class="btn btn-primary btn-icon icon-left"><i class="fas fa-plus"></i> Tambah</a>
                        </div>
                    </div>
                    <div class="card-body p-1">
                        <div class="table-responsive">
                            <table class="table table-striped table-md">
                                <tr>
                                    <th>Name</th>
                                    <th>Satuan / Simbol</th>
                                    @role('admin')
                                        <th>Dinas / SKPD</th>
                                    @endrole
                                    <th>Action</th>
                                </tr>

                                @foreach($indicators as $indicator)
                                <tr>
                                    <td>{{ $indicator->name }}</td>
                                    <td>{{ $indicator->unit->name .' / '. $indicator->unit->symbol }}</td>
                                    @role('admin')
                                        <td>{{ $indicator->office->name }}</td>
                                    @endrole
                                    <td>
                                        <form action="{{ route('indicator.destroy', $indicator) }}" method="post">
                                            @csrf
                                            @method("DELETE")
                                            
                                            <a href="{{ route('indicator.edit', $indicator) }}" class="btn btn-info btn-icon icon-left"><i class="fas fa-edit"></i> Ubah</a>
                                            <button onclick="return confirm('Yakin ingin menghapus?')" type="submit" class="btn btn-danger btn-icon icon-left"><i class="fas fa-trash"></i> Hapus</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <nav class="d-inline-block">
                            {{ $indicators->links() }}
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@include('admin.templates.partials._notifications')

resources/views/admin/indicator/recursive.blade.php
@foreach ($indicators as $indicator)
    <tr>
        <td>
            {!! $indicator->indicator_id === null ? "<b>$indicator->name</b>" : $nestedSpace . $indicator->name !!}
            {{ ' ' . $indicator->children->count() }}
        </td>
            
        <td>
            <form action="{{ route('indicator.destroy', $indicator) }}" method="post">
                @csrf
                @method("DELETE")
                
                <a href="{{ route('indicator.edit', $indicator) }}" class="btn btn-info btn-icon icon-left"><i class="fas fa-edit"></i> Ubah</a>
                <button onclick="return confirm('Yakin ingin menghapus?')" type="submit" class="btn btn-danger btn-icon icon-left"><i class="fas fa-trash"></i> Hapus</button>
            </form>
        </td>
    </tr>

    @php
        // if ($indicator->children->count() > 0) {
        //     $nestedSpace .= '<i class="fas fa-circle"></i> ';
        //     $depthLevel++;
        // } 
        // else if ($indicator->children->count() === 0 && $indicator->indicator_id !== null) {
        //     $nestedSpace = '<i class="fas fa-circle"></i> ';
        // } 
        // else {
        //     $nestedSpace = '';   
        // }

        
    @endphp

    @include('admin.indicator.recursive', ['indicators' => $indicator->children, 'nestedSpace' => $nestedSpace, 'depthLevel' => $depthLevel])

@endforeach

resources/views/admin/indicator/recursive2.blade.php
@foreach ($indicators as $indicator)

    <tr>
        <td>
            @if ($indicator->indicator_id === null)
                <ul>
                    <li>{{ $indicator->name }}</li>
                    @if ($indicator->children->count() > 0)
                        @include('admin.indicator.recursive2', ['indicators' => $indicator->children])
                    @endif
                </ul>
            @endif
        </td>
        <td> </td>
    </tr>


    {{-- <ul>
        <li>{{ $indicator->name }}</li>
        @if ($indicator->children->count() > 0)
            @include('admin.indicator.recursive2', ['indicators' => $indicator->children])
        @endif
    </ul> --}}
   

@endforeach