routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'Auth\LoginController@showLoginForm');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::middleware('auth')->prefix('admin')->namespace('Admin')->group(function () {
    Route::get('/dashboard/{id?}', 'DashboardController@index')->name('dashboard.index');
    Route::get('/report', 'ReportController@index')->name('report.index');
    Route::post('/report', 'ReportController@report')->name('report.report');
    Route::resources([
        'office' => 'OfficeController',
        'employee' => 'EmployeeController',
        'unit' => 'UnitController',
        'indicator' => 'IndicatorController',
        // 'performance-indicator' => 'PerformanceIndicatorController'
    ]);

    Route::resource('performance-indicator', 'PerformanceIndicatorController')->except([
        'edit'
    ]);
    Route::get('/performance-indicator/{office_id}/{year}/edit', 'PerformanceIndicatorController@edit')->name('performance-indicator.edit');
});


Route::prefix('api')->namespace('Api')->group(function () {
    Route::get('/office', 'PerformanceIndicatorController@offices');
    Route::get('/indicator/{id}', 'PerformanceIndicatorController@indicators');
    Route::get('/years/{id}', 'PerformanceIndicatorController@years');
});

app/Http/Controllers/Admin/ReportController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use App\Models\Office;
use App\Models\PerformanceIndicator;

class ReportController extends Controller
{
    public function index()
    {
        $offices = Office::all();
        $reports = null;
        return view('admin.report.index', compact('offices','reports'));
    }

    public function report(Request $request)
    {
        $request->validate([
            // 'office_id' => 'required',
            'year_start' => 'required',
            'year_end' => 'required'
        ]);

        $years = range($request->year_start, $request->year_end);
        $post = $request->all();

        $office_id = Auth::user()->hasRole('admin') ? $request->office_id : session('office_id');
        
        $offices = Office::all();
        $office = Office::find($office_id);
        $performance_indicators = PerformanceIndicator::where('office_id', $office_id)
                    ->whereBetween('year', [$request->year_start, $request->year_end])
                    ->orderBy('indicator_id', 'asc')
                    ->orderBy('year', 'asc')
                    ->get();

        $reports = null; 
        $last_indicator_id = null;
        $last_key = 0;
        if ($performance_indicators !== null) {
            foreach($performance_indicators as $key => $performance_indicator) {

                /** New row if indicator_id not same previously */
                if ($last_indicator_id !== $performance_indicator->indicator_id) {
                    $reports[$key]['indicator_id'] = $performance_indicator->indicator_id;
                    $reports[$key]['indicator_name'] = $performance_indicator->indicator->name;
                    $reports[$key]['unit_name'] = $performance_indicator->indicator->unit->name;
                    $reports[$key]['amount_target'][$performance_indicator->year] = $performance_indicator->amount_target;
                    $reports[$key]['amount_realization'][$performance_indicator->year] = $performance_indicator->amount_realization;
                    $reports[$key]['percentage_realization'][$performance_indicator->year] = $performance_indicator->percentage_realization;
                    $last_key = $key;            
                }
                /** Continue previous row if indicator_id same previously */
                else {
                    $reports[$last_key]['amount_target'][$performance_indicator->year] = $performance_indicator->amount_target;
                    $reports[$last_key]['amount_realization'][$performance_indicator->year] = $performance_indicator->amount_realization;
                    $reports[$last_key]['percentage_realization'][$performance_indicator->year] = $performance_indicator->percentage_realization;
                }

                $last_indicator_id = $performance_indicator->indicator_id;                
            }
        }

        /** Sorting by Indicator Name */
        if ($reports !== null) {
            $keys = array_column($reports, 'indicator_name');
            array_multisort($keys, SORT_ASC, $reports);
        }

        return view('admin.report.index', compact('reports','offices','office','years','post'));
    }
}

resources/views/admin/report/create.blade.php
@extends('admin.templates.default')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Form</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12">
                <div class="card">
                    <form action="{{ route('office.store') }}" method="post">
                        @csrf
                        <div class="card-header">
                            <h4>Form</h4>
                        </div>
                        <div class="card-body">
                    
                            <div class="form-group row">
                                <label for="name" class="col-sm-2 col-form-label">Nama</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name') }}">
                                    @error('name')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>
                    
                        </div>
                        <div class="card-footer text-right">
                            <button class="btn btn-primary mr-1" type="submit">Simpan</button>
                            <a href="{{ route('office.index') }}" class="btn btn-secondary">Batal</a>
                        </div>
                    </form>    
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/admin/report/edit.blade.php
@extends('admin.templates.default')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Form</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12">
                <div class="card">
                    <form action="{{ route('office.update', $office) }}" method="post">
                        @csrf
                        @method('PUT')

                        <div class="card-header">
                            <h4>Form</h4>
                        </div>
                        <div class="card-body">
                    
                            <div class="form-group row">
                                <label for="name" class="col-sm-2 col-form-label">Nama</label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $office->name) }}">
                                    @error('name')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>

                        </div>
                        <div class="card-footer text-right">
                            <button class="btn btn-primary mr-1" type="submit">Simpan</button>
                            <a href="{{ route('office.index') }}" class="btn btn-secondary">Batal</a>
                        </div>
                    </form>    
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/admin/report/index.blade.php
@extends('admin.templates.default')

@section('content')
<section class="section">
    <div class="section-header">
        <h1>Laporan</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12 col-md-12 col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Tabel</h4>
                    </div>
                    <div class="card-body p-3">
                        <form action="{{ route('report.report') }}" method="post">
                            @csrf

                            <div class="row">
                                @role('admin')
                                    <div class="col-sm-4">
                                        <div class="form-group">
                                            <label>Dinas / SKPD</label>
                                            <select class="form-control"name="office_id" required="true">
                                                <option value=""> - </option>
                                                @foreach ($offices as $office)
                                                    <option value="{{ $office->id }}" 
                                                        @if($reports !== null)
                                                            {{ $office->id == $post['office_id'] ? 'selected' : '' }}
                                                        @endif
                                                    >
                                                        {{ $office->name }}
                                                    </option>
                                                @endforeach
                                            </select>
                                            @error('year_start')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>
                                @endrole
                                
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        <label>Dari Tahun</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">
                                                    <i class="fas fa-calendar"></i>
                                                </div>
                                            </div>
                                            <input type="text" class="form-control datepicker" name="year_start" value="{{ $reports !== null ? $post['year_start'] : '' }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        <label>Sampai Tahun</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <div class="input-group-text">
                                                    <i class="fas fa-calendar"></i>
                                                </div>
                                            </div>
                                            <input type="text" class="form-control datepicker" name="year_end" value="{{ $reports !== null ? $post['year_end'] : '' }}">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-1">
                                    <div class="form-group">
                                        <label>&nbsp;</label>
                                        <button type="submit" class="btn btn-block btn-primary"><i class="fa fa-search"></i></button>
                                    </div>
                                </div>
                                <div class="col-sm-1">
                                    <div class="form-group">
                                        <label>&nbsp;</label>
                                        <a href="{{ route('report.index') }}" class="btn btn-block btn-warning"><i class="fa fa-eraser"></i></a>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-12">
                                    <button onclick="window.print()" class="btn btn-warning"><i class="fa fa-print"></i> Cetak</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="card-body p-1">
                        <div class="table-responsive">
                            <div id="printcontent">
                                @if($reports !== null)

                                    <span id="title" class="text-center">Laporan Data {{ $office->name }} Periode {{ $post['year_start'] }} - {{ $post['year_end'] }}</span>
                                    <br>

                                    <table class="table table-bordered table-md" style="margin-top: 0px; padding-top: 0px">
                                        {{-- Header --}}
                                        <tr>
                                            <th rowspan="3" class="align-middle text-center">Indikator Kinerja Utama</th>
                                            <th colspan="{{ count($years) }}" class="text-center">Target</th>
                                            <th colspan="{{ count($years) * 2 }}" class="text-center">Realisasi</th>
                                            <th rowspan="3" class="align-middle text-center">Satuan</th>
                                        </tr>

                                        {{-- 
                                        - Dynamic header year   
                                        --}}
                                        <tr>
                                            @for($i=0; $i<2; $i++)
                                                @foreach($years as $year)
                                                    <th colspan="{{ $i > 0 ? '2' : '' }}" class="text-center">{{ $year }}</th>
                                                @endforeach
                                            @endfor
                                        </tr>

                                        {{--
                                        - Dynamic header Angka based year
                                        --}}
                                        <tr>
                                            @for($i=0; $i<2; $i++)
                                                @if($i < 1)
                                                    @foreach($years as $year)
                                                        <th class="text-center">Angka</th>
                                                    @endforeach
                                                @else
                                                    @foreach($years as $year)
                                                        <th class="text-center">Angka</th>
                                                        <th class="text-center">%</th>
                                                    @endforeach
                                                @endif
                                            @endfor
                                        </tr>
                                    
                                        {{-- Body --}}
                                        @foreach($reports as $key => $report)
                                        <tr>
                                            <td>{{ $report['indicator_name'] }}</td>
                                            
                                            @for($i = 0; $i < 2; $i++)

                                                {{-- Amount Target Column --}}
                                                @if($i < 1)
                                                    {{--
                                                    - Print column which match with selected year 
                                                    --}}
                                                    @foreach($years as $year)
                                                        @php($year_found = false)
                                                        @foreach($report['amount_target'] as $key_year => $amount_target)
                                                            @if($key_year === $year)
                                                                <td>{{ $amount_target }}</td>
                                                                @php($year_found = true)
                                                            @endif
                                                        @endforeach

                                                        @if(!$year_found)
                                                            <td>-</td>
                                                        @endif
                                                    @endforeach
                                                    
                                                {{-- Amount Realization Column --}}
                                                @else
                                                    {{--
                                                    - Print column which match with selected year 
                                                    --}}
                                                    @foreach($years as $year)
                                                        @php($year_found = false)
                                                        @foreach($report['amount_realization'] as $key_year => $amount_realization)
                                                            @if($key_year === $year)
                                                                <td>{{ $report['amount_realization'][$year] !== null ? $report['amount_realization'][$year] : '-' }}</td>
                                                                <td>{{ number_format($report['percentage_realization'][$year], 2) !== null ? number_format($report['percentage_realization'][$year], 2) : '-' }}</td>
                                                                @php($year_found = true)
                                                            @endif
                                                        @endforeach

                                                        @if(!$year_found)
                                                            <td>-</td>
                                                            <td>-</td>
                                                        @endif
                                                    @endforeach

                                                @endif
                                            @endfor
                                            
                                            <td>{{ $report['unit_name'] }}</td>
                                        </tr>
                                        @endforeach
                                    
                                    </table>
                                @else
                                    <h1 class="text-center">Tidak ada data . . .</h1>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@push('styles')    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha256-siyOpF/pBWUPgIcQi17TLBkjvNgNQArcmwJB8YvkAgg=" crossorigin="anonymous" />
    <style>
        @media print
        {
            body * { 
                visibility: hidden;                 
            }
            #printcontent * { visibility: visible; }
            #printcontent { 
                position: absolute;  
                top: 0px;
            }
            @page { size: auto; }
        }
        #title {
            font-weight: bold;
            font-size: 30px;
            margin: 0 auto;
            display: table;
        }
    </style>
@endpush

@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha256-bqVeqGdJ7h/lYPq6xrPv/YGzMEb6dNxlfiTUHSgRCp8=" crossorigin="anonymous"></script>
    <script>
        $(document).ready(function() {
            $('.datepicker').datepicker({
                autoclose: true,
                format: "yyyy",
                minViewMode: "years"
            });
        });        
    </script> 
@endpush